### PR TITLE
Fix Python check for doc, bash-completion, fonts, and icons options

### PR DESCRIPTION
**Pull request by vilhelmgray**
Fixes: cfc56fa6 ("Introduce configure options for bash-completion, doc, fonts, and icons")

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
This seems to fix it, thanks!

**Comment by fabiangreffrath** [comment]
Sigh, this is somehow stuck in Travis CI.

**Comment by vilhelmgray** [comment]
That's strange, it looks like the checks passed but it wasn't reported to Github for some reason: https://travis-ci.org/github/chocolate-doom/chocolate-doom/builds/720636596

Is there a way to restart the checks?

**Comment by fabiangreffrath** [comment]
> Is there a way to restart the checks?

Yes, there is, but you need to be logged in. Just did so, thanks again!

**Pull request merged**
