### PR TITLE
Always try to load SKY3 when starting a new game in Doom II (resolve …

### PR DESCRIPTION
**Pull request by mfrancis95**
…#921)

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Did you check if the same logic is applied in all relevant versions of the EXE, i.e. 1.9, Ultimate and Final?

**Comment by nukeykt** [comment]
As this behavior is relevant for Linux Doom, i'd assume that all variants of 1.9 are affected too

**Comment by mfrancis95** [comment]
Here's the Linux Doom code for reference: https://github.com/id-Software/DOOM/blob/master/linuxdoom-1.10/g_game.c#L1455-L1479

**Comment by fabiangreffrath** [comment]
Indeed, PrBoom+ has the same code:

https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/g_game.c#L776

So, Choco's code seems to be a Chocoism.

**Pull request merged**
