### PR TITLE
Update github CI

### PR DESCRIPTION
**Pull request by bensuperpc**
Add ubuntu-20.04 in CI
Add CMake build in CI

Signed-off-by: Bensuperpc <bensuperpc@gmail.com>

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Hm, I'd prefer if we could just get away with ubuntu-latest.

**Comment by fabiangreffrath** [comment]
Also, it is strictly not necessary to build *all* branches on pull requests or even on push events.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by bensuperpc** [comment]
> Also, it is strictly not necessary to build *all* branches on pull requests or even on push events. 

I think that it is more practical to be able to launch the github action on branches for tests, to keep the master clean for updates... 
I updated according to your suggestions

**Comment by bensuperpc** [comment]
@fabiangreffrath Are there things to improve in PR ?

**Comment by fragglet** [comment]
Thanks for this!

**Pull request merged**
