### PR TITLE
Remove the unmaintained MSVC project

### PR DESCRIPTION
**Pull request by jmtd**
We've had several discussions, here and elsewhere, about the number of build
systems within the chocolate-doom repository. One solid outcome of this
discussion was that we will not increase the number of alternative build
systems that are present from the current number.

One of the current systems is MSVC, but the project files as committed are
out of date. This has caused some confusion from windows-oriented developers,
who are not familiar with the project, trying to try it out. (our official
build instructions still suggest using cygwin instead, and are still broken
too.)

We've had several attempts to get the MSVC projects updated, without success
(e.g. #751). Since the inclusion of the broken MSVC project procludes the
inclusion of another system, even one that someone is prepared to maintain
(e.g. #877), it should be fixed (which hasn't happened) or removed.

### CODE REVIEW

**Comment by fragglet** [comment]
If I understand correctly the expectation is that it gets replaced by a cmake-style build in the future.

I'm okay with this if @haleyjd is okay with it. As far as I'm concerned he has the deciding vote.

**Comment by haleyjd** [comment]
There are still many customized settings (optimization, building a .map file, etc) that no one has guaranteed me are going to be able to carry over to a different solution. 

You can delete the project if you want but, whenever, if ever, I am working on Chocolate for whatever reason, what I will basically end up doing is creating my own private project to work with, I suppose. I'm not familiar nor comfortable with any other workflows and don't have time/desire to spend on learning them for a hobby project at this point.

**Comment by jmtd** [comment]
@haleyjd the alternative is, whenever you work on Choco next, you commit fixes to the MSVC project files in the repo.

**Comment by jmtd** [comment]
I wrote most of the above on my phone so let me elaborate. My position is we should either have an up-to-date and working MSVC project committed, or we shouldn't have it committed as it's misleading. If someone is prepared to update it, great; but that hasn't happened (#751 is 18 months old). If it's removed, then the argument that we have too many build systems does not apply in other discussions, such as the Cmake one; I am not making a judgement on that issue here, though, I think it remains a separate issue.

Removing it does not mean it cannot be brought back, or even easily recovered by someone who wants it despite it being broken.

**Comment by fragglet** [comment]
> if ever, I am working on Chocolate for whatever reason, what I will basically end up doing is creating my own private project to work with, I suppose

I know you haven't been contributing much to the project recently (busy on many other things no doubt) but this nonetheless gives me pause; I really don't want to lose your input into the project. In particular I've always been careful to consider Chocolate Strife "your project" and don't want you to feel that we're in any way taking that away. 

Is there an acceptable compromise we can maybe reach here that would leave you happy to contribute again in future if you have time? For example, I know that cmake can generate MSVC project files. Would it be sufficient if we set up cmake and replace the old project files with the ones it generates? (ie. we keep them checked in but they're synced from the cmake files). Then I presume you should be able to pick it up and get things building with minimal fuss.

**Comment by chungy** [comment]
If we did that, we'll also have to be careful enough to generate msvc files for exactly the right version via CMake (which it supports). MSVC projects are not compatible between different versions of MSVC (eg, between 2010, 2012, 2015...), and that has been a major sticking point people on IRC get hung up, that they have the "wrong" version of MSVC compared to what the project files are for, on top of them being broken even for the right version.

@AlexMax might be able to shed more light on it, but I also think cmake doesn't make generalized project files, but instead hardcodes full paths in the files it generates. This is fine in its intended use-case being used by a single developer, but less good with committing autogenerated files.

**Comment by AlexMax** [comment]
CMake indeed does hardcode the paths.  You are not supposed to commit the contents of the build directory to your repository.  You are expected to use the CMake command or GUI tool to generate your projects before you compile or begin to work on the project yourself.

@chungy is 100% on the money with his assessment of the shortcomings of keeping Visual Studio solutions in-tree.  If you don't have the exact version of Visual Studio as the repository, you have to go through an upgrade process, which usually works for me, but then any fixes you make to the project cannot be committed back to the source repository because of the upgrade process - you might lock out earlier versions.  Also, if you're not careful, you might have modified the project in a way that makes assumptions about the local environment, though I can't speak to specifics.

I don't know of a build generator that supports Visual Studio and generates system-agnostic projects.  It might be possible, in theory, but I don't know near enough about the different versions of Visual Studio project/solution file formats to try.  All I know is that it was massively annoying for me to get the Visual Studio solution in good-enough state to contribute uncapped framerate to Crispy Doom, and then having to do it again for midiproc was more annoying still, since I had already gone through the rigmarole once, was doing it again, and nothing had changed.

**Comment by haleyjd** [comment]
> I know you haven't been contributing much to the project recently (busy on many other things no doubt) but this nonetheless gives me pause; I really don't want to lose your input into the project. 

@fragglet To be clear on this point I meant "project" in the context of Visual Studio, ie the project files. Not that I'd fork Chocolate just because of this issue. :)

I'd have no problem updating the project to 2015 and making everything build again, but the problem really is that it's a bandaid and I won't have time to be updating it after every single commit to the choco repo. So it's kind of a question as to whether or not it's worthwhile right now.

**Comment by chungy** [comment]
Updating the project doesn't seem to be resolving the underlying issue here, honestly, and [2015 isn't even the current version right now...](https://www.visualstudio.com/)

CMake generally doesn't break compatibility on new releases, it would at least secure us better against software upgrades; it's the same benefit that autotools gives us in the official build system of Chocolate Doom. Plus, given that CMake can generate make/ninja/whatever files for use on Unix, it might even be caught and repaired faster than MSVC files. (Maybe... I have doubts, but it certainly would be a lot easier.)

**Comment by JNechaevsky** [comment]
May I share some thoughts about this case? Couple of months ago I was lucky with resurrecting MSVC project files (in my fork, though). It is very easy to add missing and remove obsolete files from IDE itself to get a working build, but I probably will not handle it now by two reasons:

1. I have neither experience nor idea of what should be done in MSVC to build `midiproc.exe`.
2. For some unknown reason, while testing MSVC build I was having a **crash** on running net game from setup executable. Not sure it's because of my mess, I haven't touched netgame's code, and everything is fine with MinGW-w64 GCC (7.2.0) + CodeBlocks, so I decided to don't do further investigation.

Also, there is no necessity to update MSVC project after every commit into repository, nope, it is necessary to do this only after adding/deleting files from the project itself, which is not happening too often, especially in Chocolate project.

I'm also not a big fan of MSVC itself, but must admit that it's a de-facto for some _(ahem, many)_ Windows developers, who are not familiar with CMake, so it's probably will be a good idea to have a working MSVC solution in the source package.

Thus, my suggestion here is to ask @haleyjd to spend some time on updating MSVC solution.

**Comment by chungy** [comment]
Visual Studio 2017 includes and integrates with CMake, which should honestly make the decision even easier: https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/

**Comment by haleyjd** [comment]
> Visual Studio 2017
I offered 2015 because I don't have 2017 installed yet and have no intention on installing it while I'm still on this PC (I'll be upgrading soon though). But, whatever.

**Comment by AlexMax** [comment]
@chungy Visual Studio's CMake integration is kind of half-baked at this moment in time.  As far as I can tell, there's no GUI interface to edit cache values, just a text file that you're expected to copy paste SDL paths and such into.  The official CMake GUI is much nicer.

**Comment by turol** [comment]
For whatever it's worth, I support removing MSVC projects and moving to CMake.

**Comment by fragglet** [comment]
It sounds like @haleyjd is okay with this so I'm going to merge. Thanks and let cmaking commence.

**Comment by fragglet** [comment]
Also: I believe cmake has Codeblocks integration. Let's replace that too.

**Comment by JNechaevsky** [comment]
> I believe cmake has Codeblocks integration.

Yes, it is. Unfortunately, for Codeblocks, Cmake merges all sub-projects (games, textscreen, setup and etc) in one piece, so user will not be able, for example, to build only Doom but not Heretic and Hexen. Sorry, not sure how to explain more properly, but any way, it is working.

I've also want to note that using MSYS is _much_ easier (speaking for myself, of course) than any other previous ways to compile under Windows. And more of that, it gives all possible benefits like PNG screenshots, right from the box.

**Comment by chungy** [comment]
> Unfortunately, for Codeblocks, Cmake merges all sub-projects (games, textscreen, setup and etc) in one piece, so user will not be able, for example, to build only Doom but not Heretic and Hexen.

That might just be an issue with how the `CMakeLists.txt` is created, rather than a technical limitation of CMake itself. Regardless, building the whole project doesn't really take much time, and once you have it built, I'd hope CodeBlocks doesn't recompile files that haven't been changed since the last build.

**Comment by JNechaevsky** [comment]
Sure, it recompiles only changed files.

**Comment by AlexMax** [comment]
Allrighty then *cracks knuckles* I'll get to working on the CMake files.

**Pull request merged**
