### PR TITLE
Disable sector special 17 in gameversion 1.2

### LINKED ISSUE #1529: v1.2 DEMO1@CHURCH.WAD desync
The internal DEMO1 of [CHURCH.WAD](https://www.doomworld.com/idgames/levels/doom/a-c/church) desyncs with today's daily w32 build. 

It's a 14:37 demo that plays back all the way to the exit in the v1.2 vanilla under Dosbox 0.74-3. The desync occurs within the first 20 seconds. The first Demon is killed in two shotgun blasts in vanilla (with some help from the Imps behind it, apparently); it takes three blasts in Choco and things go rapidly downhill from there. 

Several seconds later the player takes cover in a narrow passage between the fence and the marble building at the start location. In Choco he never makes it into the passage. Same thing in Crispy and Prb+. My private forks of all three incorporate further v1.2-related fixes from #1207, yet desync the same way. Ditto for RUDE v3.1.0-pre11.

Wonder what @SmileTheory and @drfrag666 will make of it.

### PR DESCRIPTION
**Pull request by tpoppins**
The first vanilla exec to support sector special 17 (random flicker) was the official v1.4 beta. Disabling it for -gameversion 1.2 solves the desync on DEMO1 of CHURCH.WAD. Fixes #1529.

@turol: I hope I got the formatting right this time. The thing that threw me off was that almost the whole of P_SpawnSpecials is indented with TABs. Hmm, of the 1500+ lines of p_spec.c over 600 are that way. 

>Have you tested that it doesn't break any other version demos?

I don't see how it could affect anything but v1.2 compat, but since you asked I did some research. Here are a few D1 WADs with that special that have demos on DSDA:
- [02WHAT](https://dsdarchive.com/wads/02what) 4:36
- [AMAZED](https://dsdarchive.com/wads/amazed2) 4:26
- [BASETR1](https://dsdarchive.com/wads/basetr1) 1:46
- [CALGON](https://dsdarchive.com/wads/calgon)  16:32
- [CHURCH](https://dsdarchive.com/wads/church_1995) 12:09
- [WASTE](https://dsdarchive.com/wads/waste) own demos for E2M3, E2M5-E2M7 (nine in all)

all v1.9-format/UDoom-compat, no desyncs.

### CODE REVIEW

**Comment by tpoppins** [comment]
Went through the guidelines again, no idea why linter still doesn't like the styling. Either it or the guidelines have to be more explicit.

**Comment by fabiangreffrath** [comment]
> @turol: I hope I got the formatting right this time. The thing that threw me off was that almost the whole of P_SpawnSpecials is indented with TABs. Hmm, of the 1500+ lines of p_spec.c over 600 are that way.

Valid point! The original Doom source code doesn't even have a consistent formatting style, so the formatting of added or changed code has to adapt to different styles. However, we request *one specific* style with the linter CI rule. For now, I don't see how this has improved the quality of our code, but I see that this works effectively against external contributions. Not sure if it's worth it.

**Comment by turol** [comment]
I wanted to fix all the formatting in one go and commit that but @fragglet opposed. So the compromise was to enforce our style on changes.

You can run clang-format locally and see what it does to your code. Correctly picking the change from the middle of a file requires some git fu though.

In this case I think you have insufficient indeting space. You have 4+2 when you should be using 4+4.

Looks good otherwise.

Also you don't need to close and create a new PR every time, you can just push more commits on the branch. Then once the formatter oks it you can either force-push the branch or we can squash on merge (for simple enough PRs). Currently there's a bug in the linter that directly force-pushing doesn't remove outdated comments.

**Comment by tpoppins** [comment]
I'm sorry, I don't understand the 4+2 vs. 4+4 part. What do those numbers refer to?
The way it's currently indented is:
line 1469: 7 spaces
lines 1470-1472, 1474-1475: 9 spaces
line 1473: 12 spaces

clang-format is not available as a standalone package under MSYS2. LLVM wants me to download 500+MB worth of a compiler I neither need nor want to be able to run a 3MB exec. Great. I found a standalone exec, although it's v12 rather than v14 that linter uses here. Copying the cmdline from the linter job log produced a bunch of XML gobbledegook. If all else fails RTFM. OK, run with -i:
`clang-format -style=file -i --lines=1469:1475 p_spec.c`
Hmm, I didn't do anything to line 1476, and the "Files changed" tab of the PR confirms it. Why does linter uses "--lines=1469-1476" then?

No matter, I got clang-format reformat those lines with the following results:
line 1469: 10 spaces
lines 1470-1472, 1474-1475: 14 spaces
line 1473: 18 spaces

I'm using Notepad++ with "Show all characters" on, BTW; and now this section looks severely out of whack compared to the rest of the function. Is this clang-format version out of date or am I just clueless about what constitutes good formatting?

**Comment by turol** [comment]
Do you have tabs configured to 8 spaces? If so then it's just the result of having inconsistent formatting to start with. We either deal with it piecemeal as it comes up, do a massive reformatting commit or just let it be broken and slowly break even more.

**Comment by tpoppins** [comment]
The tab settings for all file types are at the default, four spaces, in Notepad++. There are no tabs in my commit. It's all spaces.
Np++ displays tabs as horizontal arrows, spaces as periods. There's no mistaking tabs for spaces with "Show all characters" on.

Just for laughs I deleted everything from my local copy of p_spec.c except for lines 1469-1475, then deleted all non-whitespace characters and line-feeds. The resulting file consists entirely of x20s, according to the HxD hex editor.

So what do I do now?

**Comment by turol** [comment]
The coding style says that tabs should be set to display as **eight** spaces but you should not use them for indentation.

I've pushed a fix for your. The surrounding code does not conform to the coding style at all. That was probably throwing you off.

**Comment by turol** [comment]
And it's apparently messing with the formatter too. This is one file that would require complete reformatting.

**Comment by tpoppins** [comment]
Thank you for the example. With tabs at 8 spaces the indentation of the code around that section changed noticeably. Still, it wasn't until I deleted everything between that section and the switch statement above that your changes started to make sense to me.

**Comment by mfrancis95** [comment]
Hi, can we consider still trying to get this through, especially since fail fast is disabled?

**Comment by turol** [comment]
Looks ok to me, can anyone say anything about actual functionality.

Should be squashed on merge.

**Review by turol — APPROVED** [review]

**Comment by mfrancis95** [comment]
I tested CHURCH.WAD and it was a slog to get through but it worked. Taking a look at the others. https://doomwiki.org/wiki/Versions_of_Doom_and_Doom_II#v1.4 makes mention of sector 17 having been added starting version 1.4.

**Comment by mfrancis95** [comment]
Everything checks out. It's obscure because this was on the mapmaker to have included that special if they were targeting 1.2 or that they shouldn't have recorded the demo in 1.2.

**Comment by tpoppins** [comment]
> Taking a look at the others. https://doomwiki.org/wiki/Versions_of_Doom_and_Doom_II#v1.4 makes mention of sector 17 having been added starting version 1.4.

No surprises there, guess who added that info. ;) Quite easy to verify: in the v1.4 beta a sector with special 17 will have flickering lighting, in v1.2 it will remain lit steadily and you get a P_PlayerInSpecialSector error if you attempt to enter it.

CHURCH.WAD's author did mess up twice. First, by using the v1.2 engine with a post-v1.2 feature; second, by setting the light levels of all the special-17 sectors and of their neighbors to 255.

**Pull request merged**
