### PR TITLE
NEWS: Replace all names refering to AXDOOMER with 'AXDOOMER'

### PR DESCRIPTION
**Pull request by AXDOOMER**
It kind of bothers me that I have been credited using four different names in NEWS.md. I replaced all of them with 'AXDOOMER' because that's the last name under which I have been credited. It will make easier to know which name to use, because it's my Github username and most people are credited under their username. 

I made sure that the lines that I modified follow the format of the file. The lines that I modified are not longer than 71 characters. 

Thanks,
Alexandre

### CODE REVIEW

**Comment by chungy** [comment]
Perfect, thanks :)

**Comment by chungy** [comment]
On second look, it seems your commit wasn't quite based on the HEAD of the repository, so other references still remain. I will try to clean it up. If I miss any, feel free to submit another PR.

**Comment by AXDOOMER** [comment]
That's weird. Something went wrong and I used an older version. 

I see: I forked and already had a fork of Chocolate-Doom on my account. 

`> git log`:
```
commit d2cb788b2be38d6e4d3bf8aa499fee1f03fd2ca1 (HEAD -> master, origin/master, origin/HEAD)
Author: Alexandre-Xavier Labonté-Lamoureux <alexandrexavier@live.ca>
Date:   Fri Mar 1 21:13:57 2019 -0500

    NEWS: Replace all names refering to AXDOOMER with 'AXDOOMER'

commit 3de5232454854ac0b64801baf2350add8f777923
Author: Alexandre-Xavier Labonté-Lamoureux <alexandrexavier@live.ca>
Date:   Fri Oct 19 17:27:18 2018 -0400

    Hexen: Call W_GenerateHashTable()
```

**Comment by AXDOOMER** [comment]
Thanks @chungy , I checked NEWS.md and you didn't miss any.

**Pull request merged**
