### PR TITLE
Clean up extern, Strife-specific bits

### PR DESCRIPTION
**Pull request by turol**
There's no crispy strife (yet) so this should not conflict

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
> There's no crispy strife (yet) so this should not conflict

Well, there is a bit of Strife in Crispy, but I guess that will buff out:

```
$ git diff --stat upstream/master -- src/strife ':!src/strife/strife_icon.c'
 src/strife/am_map.c   | 10 +++++-----
 src/strife/d_englsh.h |  5 +++++
 src/strife/d_main.c   | 36 +++++++++++++++++++++++-------------
 src/strife/f_wipe.c   |  2 ++
 src/strife/g_game.c   | 38 ++++++++++++++++++++++++++++++++------
 src/strife/m_menu.c   | 13 +++++++++----
 src/strife/p_inter.c  |  3 ++-
 src/strife/p_spec.c   |  2 +-
 src/strife/p_spec.h   |  2 +-
 src/strife/r_bsp.c    |  4 ++--
 src/strife/r_defs.h   | 14 +++++++-------
 src/strife/r_draw.c   | 38 +++++++++++++++++++-------------------
 src/strife/r_main.c   | 14 +++++++-------
 src/strife/r_plane.c  | 30 +++++++++++++++---------------
 src/strife/r_plane.h  |  8 ++++----
 src/strife/r_segs.c   |  4 ++--
 src/strife/r_state.h  |  2 +-
 src/strife/r_things.c | 12 ++++++------
 src/strife/r_things.h |  6 +++---
 src/strife/st_stuff.c |  6 ++++--
 src/strife/st_stuff.h |  4 ++--
 21 files changed, 152 insertions(+), 101 deletions(-)
```

**Review by fabiangreffrath — APPROVED** [review]

**Comment by turol** [comment]
Next PR is going to have conflicting changes so you might want to merge up now

**Comment by fabiangreffrath** [comment]
> Next PR is going to have conflicting changes so you might want to merge up now

Yep, just leave me some time, please. I can't tell for sure when I get to it.

**Comment by turol** [comment]
Too late, here it is: #1512. So... don't hit approve until you've merged? :smile:

**Comment by fragglet** [comment]
Whoops, sorry. Just saw the discussion here. I'll let Fabian merge future ones to avoid causing problems.

**Comment by fabiangreffrath** [comment]
> Whoops, sorry. Just saw the discussion here. I'll let Fabian merge future ones to avoid causing problems.

It's alright, this one went rather smooth. Could we please proceed in the order of increasing expected trouble? That is: Hexen first, then Heretic, Doom last.

**Pull request merged**
