### PR TITLE
WIP: joystick support to heretic menus

### PR DESCRIPTION
**Pull request by jmtd**
Porting from the same changes made in src/doom/m_menu.c

 • some issues with initialising key and charTyped variables in some
   paths
 • the menu gets activated immediately on start for some reason
 • save game handling not done yet
 • menu left/right via joystick broken

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
@jmtd Could you possibly fix the compiler warnings that let this branch fail during the Travis CI checks?

**Comment by jmtd** [comment]
@fabiangreffrath I can try to take a look. I don't know if rebasing would be a lot of work in the 2Y since I wrote this. Is there a prospect of a review and merge if I do the necessary rework?

**Comment by fabiangreffrath** [comment]
Yes, sure, you may request me as a reviewer.

**Comment by jmtd** [comment]
Hi, as I recall this is unfinished work anyway, so rebasing and resolving conflicts will not result in a useful PR. I haven't the time to work on this for the forseeable, so I'm going to close it. I might pick this up again one day eventually!

**Pull request closed without merging**
