### PR TITLE
strife: Add ASCII intro.

### PR DESCRIPTION
**Pull request by nukeykt**
Run game with -nograph

### CODE REVIEW

**Comment by jmtd** [comment]
I get a segfault trying this out

    frame #1: 0x0000000100011f87 chocolate-strife`V_DrawFilledBox(x=<unavailable>, y=<unavailable>, w=320, h=<unavailable>, c=0) + 215 at v_video.c:542
    frame #2: 0x000000010002a821 chocolate-strife`D_IntroTick [inlined] D_IntroBackground + 35 at d_main.c:1246
    frame #3: 0x000000010002a7fe chocolate-strife`D_IntroTick + 46 at d_main.c:1446
    frame #4: 0x000000010002b83e chocolate-strife`D_DoomMain + 3534 at d_main.c:2061

**Comment by nukeykt** [comment]
What is your command line arguments?

**Comment by jmtd** [comment]
`./src/chocolate-strife -- -iwad ~/games/strife1.wad -nosound`, first outside and then inside `lldb`. I linked against [electric fence](http://elinux.org/Electric_Fence) to get a useful backtrace.

**Comment by nukeykt** [comment]
Fixed. Thanks!
graphical_startup must be true, and you should run game with -nograph.

**Comment by chungy** [comment]
Can graphical_startup be made to have three states? I'm thinking 0 and 1 should behave as now, but introduce a 2 option that enables the ASCII intro instead.

**Comment by fragglet** [comment]
Thanks!

**Pull request merged**
