### PR TITLE
Fix SIGINT being ignored when Dehacked SHA1 warning dialog is open

### LINKED ISSUE #1048: Netgame window: SIGINT ignored when Dehacked SHA1 warning dialog open
### Background

Version of Chocolate Doom: 5c28b4c

Operating System and version: Ubuntu 17.10

Game: (Doom/Heretic/Hexen/Strife/other)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

Start a **Crispy Doom** server using `crispy-doom -privateserver`. Connect to it in **Chocolate Doom** using `chocolate-doom -connect localhost`. The warning dialog saying "Your dehacked signature does not match other players in the game..." will appear. While this dialog is open, SIGINT (`Ctrl + C` in the commandline) will be ignored, preventing the program from being terminated.

Expected behavior:

Sending SIGINT should end the program, as it does normally when the dialog is not open.

### PR DESCRIPTION
**Pull request by mfrancis95**
Fixes #1048.

### CODE REVIEW

**Comment by mfrancis95** [comment]
Not sure why the build is failing because it compiles fine for me.

**Comment by AXDOOMER** [comment]
Could be because SDL_HINT_NO_SIGNAL_HANDLERS is only available since SDL 2.0.4 and Chocolate-Doom uses an older version.

**Comment by mfrancis95** [comment]
Fixed.

**Comment by chungy** [comment]
Looks good, thanks :)

**Pull request merged**
