### PR TITLE
Install *.appdata.xml files for software centers

### LINKED ISSUE #406: Please create an AppData file for Chocolate Doom
Please consider writing and installing an AppData file with the application description and some screenshots, else Chocolate Doom looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

### PR DESCRIPTION
**Pull request by chungy**
This should resolve #406; the description text probably needs
revisement, and we still need to compose images for the screenshots
section.

### CODE REVIEW

**Comment by chungy** [comment]
I've now completed these with screenshots (hosted by the wiki).

**Comment by fragglet** [comment]
Forgot about this PR. This is ready to merge, right?

**Comment by chungy** [comment]
Yes, it should be (don't think there are any conflicts since I made it).

**Comment by fragglet** [comment]
Cool. Thanks and sorry this took so long to merge.

**Pull request merged**
