### PR TITLE
Fix MSYS2 packaging

### LINKED ISSUE #1578: Packaging on Windows doesn't work with latest MSYS2
I have all SDL2 and other DLLs installed in the recent MSYS2, when packaging I get
`
vladi@DESKTOP-0N1N2MK MINGW64 ~/chocolate-doom/pkg/win32
$ make
mkdir staging-doom
LC_ALL=C ./cp-with-libs --ldflags="-lmingw32 -mwindows -lSDL2main -lSDL2  -lsamplerate  -lpng16  -lwinmm" \
               ../../src/chocolate-doom.exe staging-doom

Missing DLLs not found in path []:
        libpng16-16.dll
        SDL2.dll
        SDL2_net.dll
        SDL2_mixer.dll
        libsamplerate-0.dll
make: *** [GNUmakefile:40: staging-doom] Error 1
`

Also when I put an IWAD file in the /src/ directory with the built exes, they won't run and give messages of the missing DLLs instead.

P.S. Building with CMake I have the same issue.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1578

### CODE REVIEW

**Comment by SoDOOManiac** [comment]
Great! Could you please do the same for CMake build?
It is more convenient in building x86 and x64 releases without any intermediate cleanup.

**Comment by rfomin** [comment]
> Could you please do the same for CMake build?

`pkg/win32` does not work with CMake. I can add packaging with the CMake system via CPack if there is interest from the maintainers.

**Comment by SoDOOManiac** [comment]
Currently even the commands
`cmake -G "Ninja" -D CMAKE_BUILD_TYPE="Release" -S . -B builddir`
`cmake --build builddir`

produce EXEs that give off missing DLL errors on launch.

Could you please fix at least this?

**Comment by rfomin** [comment]
> produce EXEs that give off missing DLL errors on launch.

This will work if you are using [vcpkg](https://github.com/microsoft/vcpkg/), it will automatically copy the dependencies. For MSYS2 there is a [mingw-bundledlls](https://github.com/mpreisler/mingw-bundledlls) script.

**Comment by SoDOOManiac** [comment]
>For MSYS2 there is a [mingw-bundledlls](https://github.com/mpreisler/mingw-bundledlls) script.

Doesn't work for recent MSYS,

`
vladi@DESKTOP-0N1N2MK MINGW64 ~/so-doom/So-Doom-5.12.2-x64/src
$ ./mingw-bundledlls --copy --upx ./so-doom.exe
Traceback (most recent call last):
  File "C:\Programs\msys64\home\vladi\so-doom\So-Doom-5.12.2-x64\src\mingw-bundledlls", line 150, in
 <module>
    main()
  File "C:\Programs\msys64\home\vladi\so-doom\So-Doom-5.12.2-x64\src\mingw-bundledlls", line 124, in
 main
    all_deps = set(gather_deps(args.exe_file, path_prefixes, set()))
  File "C:\Programs\msys64\home\vladi\so-doom\So-Doom-5.12.2-x64\src\mingw-bundledlls", line 95, in
gather_deps
    dep_path = find_full_path(dep, path_prefixes)
  File "C:\Programs\msys64\home\vladi\so-doom\So-Doom-5.12.2-x64\src\mingw-bundledlls", line 71, in
find_full_path
    raise RuntimeError(
RuntimeError: Can't find libpng16-16.dll. If it is an inbuilt Windows DLL, please add it to the blac
klist variable in the script and send a pull request!

`

**Comment by rfomin** [comment]
@fabiangreffrath Without this fix, the release.yml workflow in Crispy will fail.

**Comment by fabiangreffrath** [comment]
Oh well, what happened?

**Review by fabiangreffrath — APPROVED** [review]

**Comment by rfomin** [comment]
> Oh well, what happened?

There used to be "-L paths" in `LDFLAGS` in the MSYS2 build, now for some reason they have disappeared. I added the `--dll_path` hint as a workaround.

**Pull request merged**
