### PR TITLE
Fix GUS emulation with Midiproc.exe

### LINKED ISSUE #1244: GUS emulation not working with active Midiproc
### Background

Version of Chocolate Doom: 3.0.0 and latest dev builds

Operating System and version: Windows 10

Game: all supported

Any loaded WADs and mods (please include full command line): -

### Bug description

I've got a bug report for RD regarding GUS music synth, but it's a Chocolate Doom bug in fact.

Observed behavior: when `midiproc.exe` is running, GUS emulation is not working. Instead, standard Windows MIDI is playing. If user will remove or rename `midiproc.exe`, GUS will play normally (after loading necessary patches, of course).

Expected behavior: should GUS work properly with existing `midiproc`?

### PR DESCRIPTION
**Pull request by JNechaevsky**
By approval of @AlexMax and @fabiangreffrath. Fixes #1244.

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Oh, I see. Should be:
```
    // Don't enable it for GUS, since it handles its own volume just fine.
    if (snd_musicdevice != SNDDEVICE_GUS)
    {
        I_MidiPipe_InitServer();
    }
```
Right?

**Comment by fabiangreffrath** [comment]
Yep.

**Comment by JNechaevsky** [comment]
Fixed, apologies for carelessness.

**Comment by fabiangreffrath** [comment]
Thanks!

**Pull request merged**
