### PR TITLE
doom: support common auto-loaded files for all Doom flavors

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes: #1182

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
To provide some more context: I have a similar feature in Crispy that I'd currently like to get rid of, but it applies to all IWADs.

**Comment by fabiangreffrath** [comment]
I'll merge this after the weekend if nobody objects until then.

**Comment by fragglet** [comment]
Seems good. Only question: is "common" a good name? These only get loaded with Doom IWADs, not Heretic/Hexen/Strife - this is correct behavior but the name might suggest they would get loaded with all of them.

I can't think of a better name OTOH so I'm happy going with "common" but maybe you can think of something.

**Comment by fabiangreffrath** [comment]
We could add "doom" to the directory name and call it something like
doom-common
common-doom
doom-any
any-doom
doom-all
all-doom

or whatever you prefer. :wink:

**Comment by fragglet** [comment]
Let's go with `doom-all` then.

**Comment by fabiangreffrath** [comment]
Done so, thanks!

**Pull request merged**
