### PR TITLE
append a path delimiter to the default config dir on Windows

### PR DESCRIPTION
**Pull request by fabiangreffrath**
https://www.doomworld.com/forum/topic/86366-chocolate-doom/?page=28&tab=comments#comment-2272910

### CODE REVIEW

**Comment by turol** [comment]
`M_DirName` returns a new string which needs to be freed by the caller. You're now leaking it.

**Comment by fabiangreffrath** [comment]
It was `M_StringDuplicate("")` before the last (erroneous) commit, so at least we are not introducing a regression here.

**Review by turol — APPROVED** [review]
Looks good to me but the CI check appears to be stuck somewhere.

**Comment by chungy** [comment]
Seems to fix the basic issue while running under Wine, but it still leaves a "savegames" directory in the executable's directory rather than using it directly for saved games. That has been one of the features Chocolate Doom was explicit about, handling save games in the same manner as vanilla Doom while on Windows (the only platform where the DOS behavior still makes sense).

**Pull request merged**
