### PR TITLE
Simulate Y and N key presses with joypad when showing yes/no menus.

### PR DESCRIPTION
**Pull request by Wintermute0110**
New code is around line 1439. Diff looks bulky because I replaced some tab characters with spaces and made sure all the indentations have the correct value of 4 spaces.

### CODE REVIEW

**Comment by bb010g** [comment]
Could you separate out your formatting into its own commit, preferably after a commit with just the new code?

**Comment by Wintermute0110** [comment]
It will be a lot of work... Took me some time to change all the tabs to spaces.

**Comment by chungy** [comment]
Use `git show -w` to get a diff without whitespace changes, work from there.

**Comment by Wintermute0110** [comment]
OK, I've just read in HACKING.md that old code should not be changed. I will prepare a new clean PR ASAP.

**Comment by jmtd** [comment]
Thanks!

**Comment by Wintermute0110** [comment]
Done! @jmtd Thanks for your Git help in the previous PR comments.

**Comment by jmtd** [comment]
Good work!

**Comment by jmtd** [comment]
Someone (doesn't have to be you :)) needs to port this stuff over to the other games (heretic etc.)

**Comment by Wintermute0110** [comment]
Thanks for the merging. Maybe we can use the Doom engine to do all joystick-related code and once it's working like a charm port it to other engines.

**Comment by jmtd** [comment]
> Thanks for the merging. Maybe we can use the Doom engine to do all joystick-related code and once it's working like a charm port it to other engines.

Yeah I think that's the best approach.

**Comment by jmtd** [comment]
I'm going to poke at this a wee bit more, the ifs in this patch are not quite right, they shouldnt' reference joybmenu at all since we aren't testing the "menu" joystick button. I'm also considering adding a define like `#define JOY_BUTTON_PRESSED(x) ((x) >= 0 && (ev->data1 & (1 << (x)) != 0))` to clean up some of this file

**Pull request merged**
