### PR TITLE
 Support for Unity IWADs with widescreen assets.

### PR DESCRIPTION
**Pull request by SmileTheory**
Seemed like some low-hanging fruit.

### CODE REVIEW

**Comment by fragglet** [comment]
This PR is too intrusive IMO. I've done some inquiries and confirmed that the Unity ports are distributed with the original unaltered IWAD files, so this should be unnecessary.

Thanks regardless for taking the time to put this together.

**Comment by drfrag666** [comment]
I'm interested and i'll try to merge this into RUDE, there the wide mode framebuffer is 400 pixels wide.
https://github.com/drfrag666/RUDE

**Comment by drfrag666** [comment]
This can't be merged, i'll adjust Crispy's PR when i have time and my personal situation hopefully gets better.

**Comment by chungy** [comment]
> I don't even own the iwad.

[Not all that big of a problem](https://github.com/Doom-Utils/iwad-patches)

**Comment by drfrag666** [comment]
Thanks, that solves the iwad problem.

**Comment by drfrag666** [comment]
Done but for now without the full statusbar and bunny scroller (Crispy PR). I'm not sure it's worth, that's more sophisticated.
https://github.com/drfrag666/RUDE/commit/013541df6db36406dfef45c3b5eaecb2955ab599

**Comment by drfrag666** [comment]
All done:
https://github.com/drfrag666/RUDE/commit/545fa2ff88a6881d83b7a3597a04311572a5675a
https://github.com/drfrag666/RUDE/commit/68514828578553c3cafdf14b4d472a9d4304668b

**Pull request closed without merging**
