### PR TITLE
heretic: allow for arbitrarily long demo file names

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by turol** [comment]
Do other games require this as well?

**Comment by fabiangreffrath** [comment]
I only checked for Heretic.

**Review by turol — APPROVED** [review]
Looks ok to me but in name of consistency the other games should be changed as well.

**Comment by fabiangreffrath** [comment]
Seems like only Hexen still has a static array. Doom, Strife and now Heretic allocate dynamically.

**Pull request merged**
