### PR TITLE
check if drag-n-dropped .lmp files could be demo lumps

### PR DESCRIPTION
**Pull request by fabiangreffrath**
and pass them to the -playdemo parameter if appropriate.

@JNechaevsky @Dasperal @rfomin

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Sorry for the force-push, I had to re-indent the code.

**Comment by rfomin** [comment]
Looks good to me 👍

**Comment by JNechaevsky** [comment]
Seems to be fine on my side, just tried to drag-n-drop Doom II, Alien Vendetta and TNT demos. Not sure if I can image any odd cases for using drag-n-drop, but it's need to keep in mind that necessary IWAD should also be dropped - this is same when using command line.

P.S. Is it just me or Chocolate Doom now have an extra dll dependency - libfluidsynth-3.dll?

**Comment by rfomin** [comment]
> P.S. Is it just me or Chocolate Doom now have an extra dll dependency - libfluidsynth-3.dll?

Yes, FluidSynth music backend has been added: #1583

**Review by turol — APPROVED** [review]

**Comment by JNechaevsky** [comment]
Probably, still worth to add? Otherwise users simply will not know that such drag-n-drop is possible, or _now_ it is possible to d-n-d demos as well.

**Pull request merged**
