### PR TITLE
Automatically check formatting of modified files

### PR DESCRIPTION
**Pull request by turol**
Part of #1451.

### CODE REVIEW

**Comment by turol** [comment]
It didn't run after the force push. I wonder what's wrong.

**Comment by turol** [comment]
@fragglet ping. Is this OK? I'd really like tog get this in to see if it works correctly on PRs.

**Comment by fragglet** [comment]
Nice! Thanks for doing this, I've used clang-format at work and i thoroughly approve.

**Comment by fragglet** [comment]
@turol - I just noticed you're still not listed in `AUTHORS`. Please do add yourself :)

**Pull request closed without merging**
