### PR TITLE
Add force_software_renderer video rendering option

### PR DESCRIPTION
**Pull request by jmtd**

### CODE REVIEW

**Comment by jmtd** [comment]
Relates to #741.

**Comment by jmtd** [comment]
If you or someone ACKs this I would probably squash these two before merge; or we can wait until we have a Mesa-detection scheme working.

**Comment by jmtd** [comment]
I tested this on Linux, OS X and Windows yesterday. All are "fine", although I had to build on Windows via the VC project, which is broken and needs work for sdl2-branch, but needed *less* work than the official cygwin route (which I still haven't got working :))

Windows Remote Desktop returns null for GL_VENDOR or GL_VERSION. However, I still got around 275fps for timedemo demo1, versus around 100fps for force_software_renderer via Remote Desktop, which is interesting.

**Comment by jmtd** [comment]
On Windows not via remote desktop with an Nvidia GPU, I get null for GL_VENDOR and GL_VERSION too. It might be that the CheckGLVersion call happens too early and GL isn't initialised properly on that platform, I might try bumping it below the DrawRects that clears the screen (it *must* be initialised by then, right? even if there are delayed shenanigans happening in the background?)

**Comment by fragglet** [comment]
Since you're just using one function, you can probably use `SDL_GL_GetProcAddress()` to avoid adding a hard dependency on OpenGL.

**Comment by jmtd** [comment]
WFM on Linux (native and via VNC) and OS X. Need to do a run-time test on Windows to make sure the GL context exists when this is called otherwise we'll just get "(null)" -- not that Mesa is likely to ever be a match on that platform. Let's see what Travis CI makes of it, hopefully happy now there's no additional GL dependency.

**Comment by fragglet** [comment]
LGTM

**Pull request merged**
